<a href="https://colab.research.google.com/github/ddwijerathne/ddwijerathne/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_array = np.array([5, 3, 2, 1])
print(my_array)

[5 3 2 1]


In [3]:
my_matrix = [[3, 3, 5],
             [7, 5, 4],
             [3, 0, 9]]
np_matrix = np.array(my_matrix)
print(np_matrix)

[[3 3 5]
 [7 5 4]
 [3 0 9]]


In [4]:
print(np.arange(5, 12))

[ 5  6  7  8  9 10 11]


In [5]:
print(np.arange(5, 12, 2))

[ 5  7  9 11]


In [6]:
print(np.zeros((5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(4)

array([0.64916799, 0.56086033, 0.38097264, 0.10774734])

In [10]:
np.random.rand(5,5)

array([[0.40352889, 0.12743249, 0.28535862, 0.40208814, 0.10524341],
       [0.12616653, 0.01000798, 0.27727661, 0.29088476, 0.4667505 ],
       [0.69252326, 0.55497787, 0.66743648, 0.77480525, 0.83848321],
       [0.48566066, 0.55121924, 0.49684846, 0.68220815, 0.9852551 ],
       [0.48299532, 0.13598494, 0.5017972 , 0.51554417, 0.67579454]])

In [11]:
array_1 = np.array([[4, 3, 2, 1]])
array_2 = np.array([[3], [6], [4], [1]])
print(array_1.shape)
print(array_2.shape)
print(array_1 * array_2)

(1, 4)
(4, 1)
[[12  9  6  3]
 [24 18 12  6]
 [16 12  8  4]
 [ 4  3  2  1]]


In [12]:
array_1 = np.array([[3, 4, 2], [4, 5, 2]])
array_2 = np.array([[3, 4, 2], [4, 5, 2]])
print(array_1 + array_2)

[[ 6  8  4]
 [ 8 10  4]]


In [13]:
array_1 = np.array([3, 2, 1])
array_2 = np.array(4)
print(array_1 + array_2)

[7 6 5]


In [14]:
arr_1 = np.array([[0,1,2], [5,4,3], [0, 9, 3]])
arr_2 = np.array([1, 10, 100]).reshape(3,1)
print(arr_2.shape)

(3, 1)


In [15]:
arr_1 = np.array([[0,1,2], [5,4,3], [0, 9, 3]])
arr_2 = np.array([1, 10, 100]).reshape(3,1)
print(arr_2)

[[  1]
 [ 10]
 [100]]


In [16]:
arr_1 = np.array([[0,1,2], [5,4,3], [0, 9, 3]])
arr_2 = np.array([1, 10, 100]).reshape(3,1)
shape = (3, 3)
out = np.empty(shape, dtype=int)
for i in range(shape[0]):
    for j in range(shape[1]):
        out[i, j] = arr_1[i, j] + arr_2[i, 0]
print(out)
print(arr_1 + arr_2)

[[  1   2   3]
 [ 15  14  13]
 [100 109 103]]
[[  1   2   3]
 [ 15  14  13]
 [100 109 103]]


In [17]:
arr_1 = np.array([[4], [5], [6]])
arr_2 = np.array([[1, 2, 3]])
emp = np.empty((3, 3), dtype=int)
for i in range(3):
    for j in range(3):
        emp[i, j] = arr_1[i, 0] + arr_2[0, j]
print(emp)
print(arr_1 + arr_2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [18]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))

55
5.5
2.8722813232690143
8.25


In [19]:
print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

[ 7  9 11 13 15]
[15 40]


In [20]:
#Random Number Generation

In [24]:
rng = np.random.default_rng()
print(rng.integers(1, 7))

5
